#!/usr/bin/env python3
"""Build a browseable 20 Questions profile from Princeton WordNet 3.0.

The source graph is not edited. This experiment selects frequent noun synsets,
adds their WordNet hypernym ancestry, and chooses one deterministic display
parent when WordNet supplies multiple hypernym paths. The source synset ID and
all source hypernyms remain in the manifest.

Install/run:

    python3 -m venv /tmp/wordnet-ontology-venv
    /tmp/wordnet-ontology-venv/bin/pip install nltk
    NLTK_DATA=~/nltk_data /tmp/wordnet-ontology-venv/bin/python \
        generate_wordnet_20q.py
"""

from __future__ import annotations

import argparse
import html
import json
import math
from collections import OrderedDict, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any

from nltk.corpus import wordnet as wn


DEFAULT_SELECTED = 7000
ROOT_NAME = "entity.n.01"
SUPPRESSED_PROFILE_ROOTS = frozenset({"thing.n.08"})


def frequency(synset: Any) -> int:
    return sum(lemma.count() for lemma in synset.lemmas())


def score(synset: Any) -> float:
    """Favor familiar lemmas while giving deep concepts a small tie-break."""
    return (
        math.log1p(frequency(synset)) * 2
        + math.log1p(len(synset.lemma_names()))
        + min(synset.min_depth(), 12) * 0.03
    )


@lru_cache(maxsize=None)
def connected_to_root(synset: Any) -> bool:
    """Return whether WordNet provides a hypernym path to the display root."""
    root = wn.synset(ROOT_NAME)
    return synset == root or any(
        connected_to_root(parent) for parent in synset.hypernyms()
    )


@lru_cache(maxsize=None)
def suppressed_from_profile(synset: Any) -> bool:
    """Exclude the generic singleton branch from the game-oriented profile."""
    return synset.name() in SUPPRESSED_PROFILE_ROOTS or any(
        suppressed_from_profile(parent) for parent in synset.hypernyms()
    )


def choose_synsets(target: int) -> tuple[set[Any], list[Any]]:
    all_nouns = list(wn.all_synsets(pos="n"))
    ranked = sorted(
        (
            synset
            for synset in all_nouns
            if (
                frequency(synset) > 0
                and connected_to_root(synset)
                and not suppressed_from_profile(synset)
            )
        ),
        key=lambda synset: (-score(synset), synset.name()),
    )
    selected = set(ranked[:target])
    root = wn.synset(ROOT_NAME)
    selected.add(root)

    # Preserve every authoritative hypernym needed to connect selected nodes.
    pending = list(selected)
    while pending:
        synset = pending.pop()
        for parent in synset.hypernyms():
            if parent not in selected:
                selected.add(parent)
                pending.append(parent)
    return selected, all_nouns


def display_name(synset: Any) -> str:
    lemma = synset.lemma_names()[0].replace("_", " ")
    return f"{lemma} [{synset.name()}]"


def make_projection(selected: set[Any]) -> tuple[dict[Any, list[Any]], dict[Any, Any]]:
    root = wn.synset(ROOT_NAME)
    parents: dict[Any, Any] = {}
    children: dict[Any, list[Any]] = defaultdict(list)
    for synset in selected:
        if synset == root:
            continue
        candidates = [parent for parent in synset.hypernyms() if parent in selected]
        if not candidates:
            candidates = [root]
        # This is only a presentation tie-break; source hypernyms are kept.
        parent = min(candidates, key=lambda item: (-score(item), item.name()))
        parents[synset] = parent
        children[parent].append(synset)
    for siblings in children.values():
        siblings.sort(key=lambda item: (display_name(item).lower(), item.name()))
    return children, parents


def question_for(synset: Any) -> str:
    label = synset.lemma_names()[0].replace("_", " ")
    if synset == wn.synset(ROOT_NAME):
        return "Is it an abstraction or a physical entity?"
    return f"Is it a kind of {label}?"


def make_tree(synset: Any, children: dict[Any, list[Any]]) -> OrderedDict[str, Any]:
    result: OrderedDict[str, Any] = OrderedDict()
    result["__question__"] = question_for(synset)
    for child in children.get(synset, []):
        result[display_name(child)] = (
            make_tree(child, children) if children.get(child) else None
        )
    return result


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_yaml(tree: OrderedDict[str, Any], root_label: str) -> str:
    lines = [
        "# Generated by generate_wordnet_20q.py",
        "# Source: Princeton WordNet 3.0 noun synsets",
        "# This is a deterministic one-parent presentation projection.",
        "wordnet_3_0_20q:",
    ]

    def emit(mapping: OrderedDict[str, Any], indent: int, level: int) -> None:
        question = mapping.get("__question__")
        for name, child in mapping.items():
            if name == "__question__":
                continue
            suffix = ""
            if level <= 4 and child:
                suffix = f"  # Q: {child['__question__']}"
            lines.append(" " * indent + f"{yaml_quote(name)}:{suffix}")
            if child:
                emit(child, indent + 2, level + 1)

    lines.append("  " + f"{yaml_quote(root_label)}:")
    emit(tree, 4, 1)
    return "\n".join(lines) + "\n"


def render_html(tree: OrderedDict[str, Any], counts: dict[str, int]) -> str:
    def emit(mapping: OrderedDict[str, Any], path: tuple[str, ...], level: int) -> str:
        parts: list[str] = []
        for name, child in mapping.items():
            if name == "__question__":
                continue
            label = html.escape(name)
            path_text = html.escape(" / ".join(path + (name,)))
            if child:
                question = html.escape(child["__question__"])
                parts.append(
                    f'<details class="node" data-level="{level}" open>'
                    f"<summary>{label}</summary>"
                    f'<div class="question"><strong>Suggested question:</strong> '
                    f"{question}</div>"
                    f'<div class="path">{path_text}</div>'
                    f'<div class="children">{emit(child, path + (name,), level + 1)}</div>'
                    "</details>"
                )
            else:
                parts.append(
                    f'<div class="leaf">'
                    f"<span>{label}</span>"
                    f"<small>{path_text}</small>"
                    "</div>"
                )
        return "\n".join(parts)

    body = emit(tree, (), 1)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WordNet 3.0 20 Questions Profile</title>
<style>
:root {{ color-scheme: light dark; --accent: #2f6feb; --panel: #f6f8fa; --muted: #57606a; }}
body {{ font: 14px/1.4 system-ui, -apple-system, sans-serif; margin: 0 auto; max-width: 1200px; padding: 22px; }}
h1 {{ margin-bottom: 4px; }}
.intro, .question {{ background: var(--panel); border-left: 4px solid var(--accent); padding: 9px 13px; margin: 9px 0; }}
.controls {{ display: flex; gap: 8px; flex-wrap: wrap; margin: 16px 0; }}
input {{ flex: 1 1 300px; padding: 9px; border: 1px solid #8c959f; border-radius: 6px; }}
button {{ padding: 9px 12px; border: 1px solid #8c959f; border-radius: 6px; cursor: pointer; }}
details {{ margin: 3px 0 3px 10px; }}
summary {{ cursor: pointer; font-weight: 650; padding: 4px; }}
summary:hover {{ background: var(--panel); }}
.children {{ border-left: 1px solid #8c959f; margin-left: 8px; padding-left: 8px; }}
.question {{ color: var(--muted); font-size: .93em; }}
.path, .leaf small {{ color: var(--muted); font-size: .8em; }}
.leaf {{ display: flex; gap: 12px; justify-content: space-between; padding: 2px 5px 2px 22px; }}
.leaf:hover {{ background: var(--panel); }}
[hidden] {{ display: none !important; }}
</style>
</head>
<body>
<h1>WordNet 3.0 20 Questions Profile</h1>
<div class="intro">
  This is a browsable 20 Questions word-and-concept tree built from
  <a href="https://en.wikipedia.org/wiki/WordNet" target="_blank"
  rel="noopener">WordNet</a>, a large Princeton University lexical database
  that groups related words by meaning. It is not a list of every possible
  answer; it is a practical, familiar slice arranged from broad categories
  toward specific ones. Display nodes: {counts["selected"]:,}; terminal
  categories: {counts["leaves"]:,}. Use the suggested questions to navigate,
  search for a word, or expand the whole tree.</div>
<div class="question"><strong>Top-level question:</strong>
  Is it an abstraction or a physical entity?</div>
<div class="controls">
  <input id="search" type="search" placeholder="Search WordNet synsets or lemmas...">
  <button id="expand">Expand all</button>
  <button id="collapse">Collapse all</button>
</div>
<main id="tree">{body}</main>
<script>
const search = document.querySelector("#search");
const all = () => [...document.querySelectorAll(".node, .leaf")];
search.addEventListener("input", () => {{
  const query = search.value.trim().toLowerCase();
  all().forEach((node) => {{
    const match = !query || node.textContent.toLowerCase().includes(query);
    node.hidden = !match;
    if (match && node.classList.contains("node") && query) node.open = true;
  }});
}});
document.querySelector("#expand").onclick = () => document.querySelectorAll(".node").forEach(n => n.open = true);
document.querySelector("#collapse").onclick = () => document.querySelectorAll(".node").forEach(n => n.open = false);
</script>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=int, default=DEFAULT_SELECTED)
    parser.add_argument("--output-dir", type=Path, default=Path("."))
    args = parser.parse_args()

    selected, all_nouns = choose_synsets(args.target)
    children, parents = make_projection(selected)
    root = wn.synset(ROOT_NAME)
    tree = make_tree(root, children)
    leaves = sum(1 for synset in selected if not children.get(synset))
    counts = {
        "all_noun_synsets": len(all_nouns),
        "frequency_noun_synsets": sum(frequency(s) > 0 for s in all_nouns),
        "requested": args.target,
        "selected": len(selected),
        "branches": len(selected) - leaves,
        "leaves": leaves,
    }
    manifest = {
        "source": "Princeton WordNet",
        "version": wn.get_version(),
        "root": ROOT_NAME,
        "selection": (
            "top frequency-weighted root-connected noun synsets, excluding the "
            "generic thing.n.08 profile branch, plus complete hypernym ancestry"
        ),
        "presentation": "one deterministic parent selected from source hypernyms",
        "counts": counts,
        "synsets": {
            synset.name(): {
                "label": synset.lemma_names(),
                "gloss": synset.definition(),
                "frequency": frequency(synset),
                "hypernyms": [parent.name() for parent in synset.hypernyms()],
                "display_parent": parents.get(synset).name() if synset in parents else None,
            }
            for synset in sorted(selected, key=lambda item: item.name())
        },
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "wordnet_20q.yaml").write_text(
        render_yaml(tree, display_name(root)), encoding="utf-8"
    )
    (args.output_dir / "wordnet_20q.html").write_text(
        render_html(tree, counts), encoding="utf-8"
    )
    (args.output_dir / "wordnet_20q_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(counts, sort_keys=True))


if __name__ == "__main__":
    main()
