#!/usr/bin/env python3
"""Generate a practical, question-oriented noun hierarchy for 20 Questions.

The ontology is deliberately organized by high-value game questions instead of
strict biological or academic taxonomy.  It is dependency-free and deterministic:

    python3 generate_20q_hierarchy.py
    python3 generate_20q_hierarchy.py --output my-20q-tree.yaml

The output is ordinary YAML with comments on every branch through level four.
Empty mappings are terminal noun categories, so IntelliJ can fold every branch.
"""

from __future__ import annotations

import argparse
import html
from collections import OrderedDict
from pathlib import Path
from typing import Mapping


Tree = OrderedDict[str, "Tree | None"]


def branch(question: str, *groups: Tree, **children: Tree | None) -> Tree:
    """Attach a discriminator to a mapping without adding YAML machinery."""
    result: Tree = OrderedDict()
    result["__question__"] = question  # consumed by the renderer
    for group in groups:
        result.update(group)
    result.update(children)
    return result


def leaves(*names: str) -> Tree:
    return OrderedDict((name, None) for name in names)


def render_yaml(tree: Mapping[str, Tree | None], root_name: str) -> str:
    lines = [
        "# Generated by generate_20q_hierarchy.py",
        "# Ask the highest-level questions first; switch branches as soon as the",
        "# answer sharply reduces the remaining candidate set.",
        f"{root_name}:",
    ]

    def emit(mapping: Mapping[str, Tree | None], indent: int, level: int) -> None:
        question = mapping.get("__question__")
        for name, child in mapping.items():
            if name == "__question__":
                continue
            display_name = name.replace("_", " ")
            suffix = ""
            if child is not None and level <= 4:
                child_question = child.get("__question__", "Does it belong to this category?")
                suffix = f"  # Q: {child_question}"
            lines.append(" " * indent + f"{display_name}:{suffix}")
            if child:
                emit(child, indent + 2, level + 1)

    emit(tree, 2, 1)
    return "\n".join(lines) + "\n"


def render_html(tree: Mapping[str, Tree | None], title: str) -> str:
    """Render a self-contained browser with collapsible branches and questions."""
    def searchable(mapping: Mapping[str, Tree | None]) -> str:
        values = []
        for name, child in mapping.items():
            if name != "__question__":
                values.append(name.replace("_", " "))
                if child:
                    values.append(searchable(child))
        return " ".join(values)

    def emit(mapping: Mapping[str, Tree | None], level: int, path: tuple[str, ...]) -> str:
        parts = []
        for name, child in mapping.items():
            if name == "__question__":
                continue
            label = name.replace("_", " ")
            escaped_label = html.escape(label)
            escaped_path = html.escape(" / ".join(path + (label,)))
            if child:
                question = html.escape(child.get("__question__", "Does it belong here?"))
                search_text = html.escape(searchable(child), quote=True)
                open_attr = " open" if level == 1 else ""
                parts.append(
                    f'<details class="node" data-search="{search_text}"{open_attr}>'
                    f'<summary>{escaped_label}</summary>'
                    f'<div class="question"><strong>Suggested question:</strong> {question}</div>'
                    f'<div class="path">{escaped_path}</div>'
                    f'<div class="children">{emit(child, level + 1, path + (label,))}</div>'
                    "</details>"
                )
            else:
                parts.append(
                    f'<div class="leaf" data-search="{html.escape(label.lower(), quote=True)}">'
                    f'<span>{escaped_label}</span>'
                    f'<small>{escaped_path}</small>'
                    "</div>"
                )
        return "\n".join(parts)

    root_question = html.escape(tree.get("__question__", "What kind of thing is it?"))
    body = emit(tree, 1, ())
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>
:root {{ color-scheme: light dark; --accent: #2f6feb; --panel: #f6f8fa; --muted: #57606a; }}
body {{ font: 15px/1.45 system-ui, -apple-system, sans-serif; margin: 0 auto; max-width: 1100px; padding: 24px; }}
h1 {{ margin-bottom: 6px; }}
.intro, .question {{ background: var(--panel); border-left: 4px solid var(--accent); padding: 10px 14px; margin: 10px 0; }}
.controls {{ display: flex; gap: 8px; flex-wrap: wrap; margin: 18px 0; }}
input {{ flex: 1 1 280px; padding: 9px; border: 1px solid #8c959f; border-radius: 6px; }}
button {{ padding: 9px 12px; border: 1px solid #8c959f; border-radius: 6px; cursor: pointer; }}
details {{ margin: 4px 0 4px 12px; }}
summary {{ cursor: pointer; font-weight: 650; padding: 5px; }}
summary:hover {{ background: var(--panel); }}
.children {{ border-left: 1px solid #8c959f; margin-left: 9px; padding-left: 8px; }}
.question {{ color: var(--muted); font-size: .94em; }}
.path, .leaf small {{ color: var(--muted); font-size: .82em; }}
.leaf {{ display: flex; gap: 12px; justify-content: space-between; padding: 3px 6px 3px 25px; }}
.leaf:hover {{ background: var(--panel); }}
[hidden] {{ display: none !important; }}
</style>
</head>
<body>
<h1>{html.escape(title)}</h1>
<div class="intro"><strong>Opening question:</strong> {root_question}</div>
<div class="controls">
  <input id="search" type="search" placeholder="Search nouns or categories...">
  <button id="expand">Expand all</button>
  <button id="collapse">Collapse all</button>
</div>
<main id="tree">{body}</main>
<script>
const nodes = [...document.querySelectorAll(".node, .leaf")];
const search = document.querySelector("#search");
search.addEventListener("input", () => {{
  const query = search.value.trim().toLowerCase();
  document.querySelectorAll(".node, .leaf").forEach((node) => {{
    const match = !query || node.dataset.search.toLowerCase().includes(query);
    node.hidden = !match;
    if (match && node.classList.contains("node") && query) node.open = true;
  }});
  if (query) document.querySelectorAll(".node").forEach((node) => {{
    if (node.querySelector(".leaf:not([hidden]), .node:not([hidden])")) node.open = true;
  }});
}});
document.querySelector("#expand").onclick = () => document.querySelectorAll(".node").forEach(n => n.open = true);
document.querySelector("#collapse").onclick = () => document.querySelectorAll(".node").forEach(n => n.open = false);
</script>
</body>
</html>
"""


def make_tree() -> Tree:
    """Return the curated hierarchy.

    The first four levels use broad, near-binary or categorical discriminators.
    Deeper levels become functional and familiar, ending in playable noun
    categories rather than obscure scientific taxa.
    """
    return branch(
        "Is the answer primarily physical, living, or abstract?",
        Physical=branch(
            "Can it be touched or located in physical space?",
            Living=branch(
                "Is it a whole organism, a part, or a biological product?",
                Animal=branch(
                    "Does it move voluntarily and consume other organisms or organic matter?",
                    Vertebrate=branch(
                        "Does it have an internal backbone?",
                        Mammal=branch(
                            "Is it mainly associated with people, land, or water?",
                            Companion_and_work=branch(
                                "Is it commonly kept, trained, or used by people?",
                                leaves("dog", "cat", "horse", "cow", "pig", "goat", "sheep",
                                       "rabbit", "hamster", "mouse", "rat", "donkey", "camel",
                                       "llama", "alpaca", "elephant"),
                            ),
                            Wild_land=branch(
                                "Is it a predator, grazer, or omnivore?",
                                leaves("lion", "tiger", "bear", "wolf", "fox", "deer",
                                       "moose", "elk", "giraffe", "zebra", "rhinoceros",
                                       "hippopotamus", "gorilla", "chimpanzee", "kangaroo",
                                       "panda", "koala", "squirrel", "skunk", "raccoon"),
                            ),
                            Marine_and_flying=branch(
                                "Does it primarily live in water or fly?",
                                leaves("whale", "dolphin", "seal", "walrus", "bat",
                                       "monkey", "sloth", "otter", "beaver"),
                            ),
                        ),
                        Bird=branch(
                            "Is it chiefly a familiar wild bird, domestic bird, or bird of prey?",
                            leaves("chicken", "duck", "goose", "turkey", "penguin", "eagle",
                                   "hawk", "owl", "parrot", "pigeon", "crow", "raven",
                                   "robin", "sparrow", "flamingo", "peacock", "swan",
                                   "woodpecker", "hummingbird"),
                        ),
                        Reptile_and_amphibian=branch(
                            "Does it have scales, or does it undergo a water-to-land life cycle?",
                            leaves("snake", "lizard", "turtle", "tortoise", "crocodile",
                                   "alligator", "frog", "toad", "salamander", "newt"),
                        ),
                        Fish=branch(
                            "Is it a common food fish, aquarium fish, or large ocean fish?",
                            leaves("salmon", "trout", "tuna", "cod", "bass", "carp",
                                   "goldfish", "shark", "ray", "seahorse", "eel", "piranha"),
                        ),
                    ),
                    Invertebrate=branch(
                        "Does it have jointed legs, a shell, or a soft-bodied form?",
                        Insect_and_arthropod=branch(
                            "Does it have six legs, eight legs, or many legs?",
                            leaves("ant", "bee", "wasp", "fly", "mosquito", "butterfly",
                                   "moth", "beetle", "ladybug", "grasshopper", "cricket",
                                   "dragonfly", "spider", "scorpion", "tick", "flea",
                                   "centipede", "millipede"),
                        ),
                        Mollusk_and_worm=branch(
                            "Does it have a shell or a long, soft, wormlike body?",
                            leaves("snail", "slug", "clam", "oyster", "mussel", "scallop",
                                   "squid", "octopus", "earthworm", "leech"),
                        ),
                        Aquatic_invertebrate=branch(
                            "Does it live mainly in saltwater, freshwater, or a damp habitat?",
                            leaves("crab", "lobster", "shrimp", "jellyfish", "coral",
                                   "starfish", "sea urchin", "sponge"),
                        ),
                    ),
                ),
                Plant=branch(
                    "Is it mainly recognized as food, a tree, a flower, or a wild plant?",
                    Food_crop=branch(
                        "Is the edible part a fruit, vegetable, grain, legume, or herb?",
                        leaves("apple", "orange", "banana", "lemon", "grape", "strawberry",
                               "watermelon", "tomato", "potato", "carrot", "onion", "garlic",
                               "lettuce", "spinach", "corn", "wheat", "rice", "bean",
                               "pea", "soybean", "pepper", "mushroom", "coffee plant",
                               "tea plant", "cocoa plant"),
                    ),
                    Tree_and_shrub=branch(
                        "Is it chiefly valued for wood, fruit, shade, or ornament?",
                        leaves("oak", "pine", "maple", "birch", "willow", "palm",
                               "cedar", "redwood", "sequoia", "cactus", "bamboo",
                               "rose bush", "grapevine"),
                    ),
                    Flower_and_garden=branch(
                        "Is it a showy flower, bulb, houseplant, or garden plant?",
                        leaves("rose", "tulip", "daisy", "sunflower", "lily", "orchid",
                               "violet", "lavender", "daffodil", "marigold", "fern",
                               "ivy", "moss", "grass", "weed"),
                    ),
                ),
                Fungus_and_microbe=branch(
                    "Is it a mushroom, mold, yeast, bacterium, or microscopic agent?",
                    leaves("mushroom", "truffle", "mold", "yeast", "bacterium",
                           "virus", "alga", "plankton"),
                ),
                Biological_part_or_product=branch(
                    "Is it an anatomical part, a secretion, or a processed biological material?",
                    leaves("bone", "tooth", "hair", "feather", "skin", "blood", "egg",
                           "seed", "pollen", "wood", "milk", "honey", "silk", "leather"),
                ),
            ),
            Artifact=branch(
                "Was it intentionally made by people?",
                Tool_and_instrument=branch(
                    "Is its main role cutting, fastening, measuring, striking, or shaping?",
                    Cutting_and_shaping=branch(
                        "Does it have an edge, teeth, abrasive surface, or shaping bit?",
                        leaves("knife", "scissors", "saw", "axe", "razor", "chisel",
                               "plane", "file", "grater", "drill", "screwdriver"),
                    ),
                    Fastening_and_gripping=branch(
                        "Does it hold, turn, clamp, join, or fasten something?",
                        leaves("hammer", "wrench", "pliers", "clamp", "vise", "screw",
                               "nail", "bolt", "staple", "tape measure", "level"),
                    ),
                    Measuring_and_observing=branch(
                        "Does it quantify, detect, magnify, or record a physical property?",
                        leaves("ruler", "scale", "thermometer", "clock", "watch",
                               "compass", "microscope", "telescope", "camera",
                               "binoculars", "calculator"),
                    ),
                ),
                Device_and_machine=branch(
                    "Does it use electricity, an engine, or a network to perform work?",
                    leaves("phone", "computer", "tablet", "television", "radio", "printer",
                           "robot", "refrigerator", "oven", "washing machine", "vacuum",
                           "fan", "air conditioner", "generator", "motor", "battery",
                           "light bulb", "remote control"),
                ),
                Container_and_household=branch(
                    "Is its main purpose to contain, prepare, clean, furnish, or illuminate?",
                    Kitchen=branch(
                        "Is it used for cooking, cutting, serving, or storing food?",
                        leaves("pot", "pan", "kettle", "bowl", "plate", "cup", "glass",
                               "mug", "fork", "spoon", "chopsticks", "whisk", "spatula",
                               "ladle", "colander", "bottle", "jar", "can", "basket"),
                    ),
                    Home=branch(
                        "Is it furniture, bedding, cleaning equipment, or a decorative object?",
                        leaves("chair", "table", "desk", "bed", "sofa", "shelf", "cabinet",
                               "drawer", "mirror", "lamp", "candle", "towel", "blanket",
                               "pillow", "broom", "mop", "bucket", "umbrella", "key",
                               "lock", "door", "window"),
                    ),
                ),
                Garment_and_personal_item=branch(
                    "Is it worn, carried, read, played with, or used for personal identity?",
                    leaves("shirt", "coat", "dress", "pants", "skirt", "shoe", "boot",
                           "sock", "hat", "glove", "scarf", "belt", "pajamas", "uniform",
                           "ring", "necklace", "glasses", "wallet", "backpack", "handbag",
                           "book", "newspaper", "toy", "doll", "ball", "puzzle"),
                ),
                Vehicle_and_structure=branch(
                    "Does it transport people or goods, or provide a place to live/work?",
                    Vehicle=branch(
                        "Does it travel mainly by road, rail, water, or air?",
                        leaves("car", "truck", "bus", "bicycle", "motorcycle", "train",
                               "tractor", "ship", "boat", "submarine", "airplane",
                               "helicopter", "rocket", "spaceship", "wheelchair"),
                    ),
                    Structure=branch(
                        "Is it a home, public building, infrastructure, or monument?",
                        leaves("house", "apartment", "school", "hospital", "church",
                               "store", "office", "factory", "restaurant", "castle",
                               "bridge", "road", "dam", "tower", "stadium", "temple",
                               "pyramid", "statue", "fence", "tent"),
                    ),
                ),
            ),
            Natural_substance=branch(
                "Is it primarily a material, a mineral, a physical force, or a phenomenon?",
                Material=branch(
                    "Is it solid, liquid, gas, or a manufactured substance?",
                    leaves("water", "ice", "steam", "air", "fire", "smoke", "soil",
                           "sand", "clay", "mud", "rock", "stone", "metal", "iron",
                           "steel", "gold", "silver", "copper", "glass", "plastic",
                           "paper", "rubber", "oil", "gasoline", "salt", "sugar"),
                ),
                Earth_and_weather=branch(
                    "Is it a landform, water feature, weather event, or natural hazard?",
                    leaves("mountain", "hill", "valley", "canyon", "cave", "island",
                           "beach", "desert", "forest", "river", "lake", "ocean",
                           "waterfall", "cloud", "rain", "snow", "wind", "storm",
                           "lightning", "rainbow", "earthquake", "volcano", "flood",
                           "hurricane", "tornado"),
                ),
                Space_and_celestial=branch(
                    "Is it a planet, star, moon, small body, or large cosmic system?",
                    leaves("Sun", "Moon", "Earth", "planet", "star", "comet", "asteroid",
                           "meteor", "galaxy", "nebula", "black hole", "constellation"),
                ),
            ),
            Geographic_entity=branch(
                "Is it a natural region, a human settlement, a political unit, or a route?",
                Natural_region=branch(
                    "Is it identified mainly by terrain, climate, ecosystem, or water?",
                    leaves("Arctic", "Antarctica", "Amazon", "Sahara", "Pacific Ocean",
                           "Atlantic Ocean", "Rocky Mountains", "Alps", "Grand Canyon",
                           "Great Barrier Reef", "national park", "island"),
                ),
                Human_place=branch(
                    "Is it a city, country, neighborhood, institution, or landmark?",
                    leaves("New York", "London", "Paris", "Tokyo", "Rome", "Washington",
                           "United States", "Canada", "Mexico", "China", "India",
                           "France", "city", "village", "capital", "airport", "museum"),
                ),
            ),
        ),
        Abstract=branch(
            "Is it chiefly a person/entity, event, information, social system, or idea?",
            Person_or_character=branch(
                "Is it a real individual, a fictional character, a mythic being, or a role?",
                Historical_and_contemporary=branch(
                    "Is the person known mainly for politics, science, art, sport, or exploration?",
                    leaves("Abraham Lincoln", "George Washington", "Cleopatra", "Julius Caesar",
                           "Napoleon", "Mahatma Gandhi", "Martin Luther King Jr.",
                           "Albert Einstein", "Marie Curie", "William Shakespeare",
                           "Leonardo da Vinci", "Beethoven", "Elvis Presley",
                           "Michael Jackson", "Serena Williams", "Michael Jordan",
                           "Neil Armstrong", "Amelia Earhart", "Queen Elizabeth II"),
                ),
                Fictional_and_mythic=branch(
                    "Is it from literature, film, television, games, religion, or mythology?",
                    leaves("Harry Potter", "Sherlock Holmes", "James Bond", "Cinderella",
                           "Santa Claus", "Superman", "Batman", "Spider-Man", "Mickey Mouse",
                           "Darth Vader", "Yoda", "Frodo", "Gandalf", "Hercules",
                           "Zeus", "Thor", "dragon", "unicorn", "vampire", "zombie",
                           "ghost", "mermaid", "fairy", "wizard", "detective", "pirate"),
                ),
                Role_and_group_member=branch(
                    "Is it a profession, relationship, rank, identity, or social role?",
                    leaves("parent", "child", "friend", "neighbor", "teacher", "doctor",
                           "nurse", "lawyer", "engineer", "artist", "musician", "farmer",
                           "soldier", "pilot", "chef", "president", "king", "queen",
                           "hero", "villain", "celebrity", "athlete"),
                ),
            ),
            Organization_and_institution=branch(
                "Is it a government, business, educational body, association, or group?",
                leaves("country", "government", "army", "police", "company", "corporation",
                       "brand", "school", "university", "hospital", "church", "club",
                       "team", "band", "family", "community", "political party",
                       "nonprofit", "court", "parliament"),
            ),
            Event_and_time=branch(
                "Is it a recurring natural/social event, a historical event, or a time unit?",
                leaves("birthday", "wedding", "holiday", "festival", "party", "concert",
                       "game", "race", "battle", "war", "revolution", "election",
                       "ceremony", "meeting", "journey", "disaster", "day", "week",
                       "month", "year", "century", "season", "past", "future"),
            ),
            Information_and_media=branch(
                "Is it a language symbol, document, artwork, story, sound, or digital object?",
                leaves("word", "name", "number", "letter", "symbol", "question", "answer",
                       "fact", "idea", "map", "letter", "document", "contract", "law",
                       "book", "novel", "poem", "song", "film", "photograph", "painting",
                       "sculpture", "news", "website", "email", "message", "password",
                       "program", "algorithm", "database"),
            ),
            State_and_relation=branch(
                "Is it a quality, emotion, relationship, process, rule, or value judgment?",
                leaves("love", "hate", "friendship", "family", "anger", "fear", "joy",
                       "sadness", "hope", "dream", "memory", "knowledge", "truth",
                       "beauty", "freedom", "justice", "peace", "war", "power", "money",
                       "health", "death", "life", "birth", "change", "motion", "speed",
                       "size", "color", "shape", "cause", "effect", "problem", "solution",
                       "rule", "plan", "promise", "secret", "luck", "chance", "number",
                       "mathematics", "science", "religion", "language", "culture"),
            ),
        ),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("20_questions_hierarchy.yaml"),
        help="YAML path to write (default: 20_questions_hierarchy.yaml)",
    )
    parser.add_argument(
        "--html-output",
        type=Path,
        default=Path("index.html"),
        help="HTML path to write (default: index.html)",
    )
    args = parser.parse_args()
    tree = make_tree()
    yaml_output = render_yaml(tree, "20_questions_noun_hierarchy")
    html_output = render_html(tree, "20 Questions Noun Hierarchy")
    args.output.write_text(yaml_output, encoding="utf-8")
    args.html_output.write_text(html_output, encoding="utf-8")
    print(f"Wrote {args.output} ({yaml_output.count(chr(10)) - 1} lines)")
    print(f"Wrote {args.html_output} ({html_output.count(chr(10)) - 1} lines)")


if __name__ == "__main__":
    main()
